### ISSUE TITLE
Integrate basic authentication

### ISSUE THREAD

**Issue by soveran** [syro/satz#1]
A very common use case is to restrict access to the application with Basic Auth. One idea is to integrate [Basica](https://github.com/syro).

**Comment by elcuervo** [comment]
Currently only basic auth is supported: https://github.com/syro/satz/blob/17d03bde169f529dce93bc056e5c160efd183b36/lib/satz.rb#L47-L56. The "Basic" part of the header is being ignored so every request with an `Authentication:` header will be attempted to get `Base64` decoded.

How do you feel about the other types? about renaming `auth` to `basic_auth`?
Maybe some form of configuration for `auth`?

Thinking out loud here ^_^. I've been facing with `Basic`, `Digest`, `Bearer` and `Token` but that's mostly because of research :)

**Comment by soveran** [comment]
We can choose between these different approaches: A) standardize on one method (we can decide which one); B) support different strategies, or C) make the strategy user defined and pluggable when creating the app.

I started with `basic_auth`, but then decided to go for option A and standardize on Basic Auth, so I renamed the command to just `auth`. As I don't have a lot of experience with other strategies, so we can first weight the pros and cons of A, B and C, and if we go for A or B we can decide which methods are desirable. I faced a similar problem with the serialization: I used `JSON` by default, but as explained in #2 there are good arguments for letting the user customize which serializer to use. I'm currently in the process of implementing that change, but that's only because the performance increase of going from `JSON` to `Oj` is too big to be ignored. If that weren't the case, I would have favored using just `JSON` as a standard. In the case of auth strategies, the ideal would be to check if one of them is better than the others and standardize on that one. If for some use case that's not good enough, there's always the possibility of subclassing `Satz` and providing a different auth strategy.

**Comment by soveran** [comment]
@elcuervo I think I will rename it to `basic_auth` for now, sounds good? In the future we can explore other methods. We can also leave it as `auth`, as it's a good name for the default behaviour anyway.

**Comment by soveran** [comment]
I released it as just `auth` in 0.0.3, but mostly to see how it feels. In the future we can revisit the change.

**Comment by elcuervo** [comment]
Sounds good. I'll probably create a PR with diferente auth strategies when I need it. Cheers ^_^
