### ISSUE TITLE
JSON performances [note]

### ISSUE THREAD

**Issue by solyarisoftware** [syro/satz#2]
Hi Michel
just a note! not an issue and please label as note or close it 

Just because Syro (and Satz) are for sure a performance heros :), 
maybe JSON dump/load could be made with fast Pether Olher's [Oj](https://github.com/ohler55/oj) gem, maybe through [MultiJson](https://github.com/intridea/multi_json) Oj wrapper too.

In facts my note here is just an excuse to thank you for your works (micromachine, mote, etc. etc. ) around minimalism in Ruby :)
respect
giorgio

**Comment by soveran** [comment]
Ciao Giorgio! Thanks a lot for the tip and for the continued support, I really appreciate it and I'm glad you gave me the chance to let you know :-)

What you say is indeed important, I will try to refactor Satz so that the serializer is pluggable. JSON as it is now could be the default, as it's part of the standard library, but in the docs we can describe how to replace the serializer with `Oj`, `MultiJson`, or in fact any other serialization library. I'm thinking now that it doesn't have to be restricted to JSON, so if possible I will leave it as generic as possible. Again, thanks a lot for the tip, very interesting idea :-)

**Comment by solyarisoftware** [comment]
Ciao Michel!
Yes, I fully agree about a "serialization agnostic" pluggable approach!
I'll help as I can, also to return what I learn reading your code.
thanks

**Comment by soveran** [comment]
@solyaris I have a branch that allows users to provide a custom serializer object, [here's the documentation](https://github.com/syro/satz/tree/9e1f2e545b3929d541820cc6105c733aef49779a#serialization) for it.

**Comment by solyarisoftware** [comment]
Yes, Michel
I read your code and to serialize using by example @ohler55 [Oj](https://github.com/ohler55/oj) JSON optimizer is now simple as:

```
require 'Oj'
Satz.serializer = Oj
```

And to just use flat text (instead of JSON) is just a matter of write two micro methods.
Great @soveran ! :)

**Comment by soveran** [comment]
@solyaris I will probably release a new version tomorrow. Thanks a lot for your input, it was extremely valuable :-)
